const HYDRO_STATION="https://www.hydro-1.net/Data/STATION/";
const stations=[
{id:"W.25",name:"บ้านร่องเคาะ อ.วังเหนือ",river:"แม่น้ำวัง",province:"ลำปาง",lat:19.0374,lng:99.6165,bankfull:5.34,sourceType:"derived",sourceUrl:HYDRO_STATION+"W.25.html",thresholdNote:"คำนวณจากตลิ่งฝั่งต่ำ 387.239 − ศูนย์เสา 381.903 ม.รทก."},
{id:"W.16A",name:"บ้านไฮ อ.แจ้ห่ม",river:"แม่น้ำวัง",province:"ลำปาง",lat:18.7853,lng:99.63,bankfull:6.21,sourceType:"derived",sourceUrl:HYDRO_STATION+"W.16A.html",thresholdNote:"คำนวณจากตลิ่งฝั่งต่ำ 310.214 − ศูนย์เสา 304.000 ม.รทก."},
{id:"W.17",name:"บ้านหนองนาว อ.แจ้ห่ม",river:"น้ำแม่สอย",province:"ลำปาง",lat:18.72236,lng:99.56721,bankfull:4.24,sourceType:"derived",sourceUrl:HYDRO_STATION+"W.17.html",thresholdNote:"คำนวณจากตลิ่งฝั่งต่ำ 296.240 − ศูนย์เสา 292.000 ม.รทก."},
{id:"W.26",name:"บ้านห้วยแม่ต๋า อ.แจ้ห่ม",river:"ห้วยแม่ต๋า",province:"ลำปาง",lat:18.59602,lng:99.62205,bankfull:null,sourceType:"unknown",sourceUrl:HYDRO_STATION+"W.26.html",thresholdNote:"ทะเบียนสถานียังไม่ระบุระดับตลิ่งและระดับศูนย์เสา"},
{id:"W.21",name:"บ้านท่าเดื่อ อ.เมืองลำปาง",river:"แม่น้ำวัง",province:"ลำปาง",lat:18.34317,lng:99.53699,bankfull:7.92,sourceType:"derived",sourceUrl:HYDRO_STATION+"W.21.html",thresholdNote:"คำนวณจากตลิ่งฝั่งต่ำ 239.918 − ศูนย์เสา 232.000 ม.รทก."},
{id:"W.1C",name:"สะพานเสตุวารี อ.เมืองลำปาง",river:"แม่น้ำวัง",province:"ลำปาง",lat:18.29971,lng:99.51115,bankfull:5.20,watchLevel:4.16,sourceType:"official",sourceUrl:"https://www.hydro-1.net/index1.html",thresholdNote:"ระดับตลิ่ง 5.20 ม.; เฝ้าระวังตั้งแต่ 4.16 ม. ตามเอกสารเกณฑ์สถานี"},
{id:"W.20",name:"บ้านท่าล้อ ต.บ่อแฮ้ว",river:"น้ำแม่ตุ๋ย",province:"ลำปาง",lat:18.31091,lng:99.45782,bankfull:7.64,sourceType:"derived",sourceUrl:HYDRO_STATION+"W.20.html",thresholdNote:"คำนวณจากตลิ่งฝั่งต่ำ 238.059 − ศูนย์เสา 230.420 ม.รทก."},
{id:"W.5A",name:"บ้านเกาะคา ต.ศาลา",river:"แม่น้ำวัง",province:"ลำปาง",lat:18.19161,lng:99.39712,bankfull:null,sourceType:"unknown",sourceUrl:HYDRO_STATION+"W.5A.html",thresholdNote:"ทะเบียนสถานียังไม่ระบุระดับตลิ่งและระดับศูนย์เสา"},
{id:"W.22",name:"บ้านวังพร้าว อ.เกาะคา",river:"น้ำแม่จาง",province:"ลำปาง",lat:18.14451,lng:99.40839,bankfull:5.99,sourceType:"derived",sourceUrl:HYDRO_STATION+"W.22.html",thresholdNote:"คำนวณจากตลิ่งฝั่งต่ำ 221.155 − ศูนย์เสา 215.161 ม.รทก."},
{id:"W.18A",name:"บ้านสบต๋ำ อ.เกาะคา",river:"น้ำแม่ต๋ำ",province:"ลำปาง",lat:18.07048,lng:99.32276,bankfull:null,sourceType:"unknown",sourceUrl:"https://www.hydro-1.net/index1.html",thresholdNote:"ยังไม่พบเอกสารทางการออนไลน์ที่ระบุระดับตลิ่ง"},
{id:"W.6B",name:"บ้านหล่าย อ.สบปราบ",river:"แม่น้ำวัง",province:"ลำปาง",lat:17.89022,lng:99.3279,bankfull:null,sourceType:"unknown",sourceUrl:"https://www.hydro-1.net/index1.html",thresholdNote:"ยังไม่พบเอกสารทางการออนไลน์ที่ระบุระดับตลิ่ง"},
{id:"W.3A",name:"บ้านดอนชัย อ.เถิน",river:"แม่น้ำวัง",province:"ลำปาง",lat:17.64152,lng:99.2319,bankfull:4.80,watchLevel:3.84,sourceType:"official",sourceUrl:"https://www.hydro-1.net/index1.html",thresholdNote:"ระดับตลิ่ง 4.80 ม.; เฝ้าระวังตั้งแต่ 3.84 ม. ตามเอกสารเกณฑ์สถานี"},
{id:"W.23",name:"บ้านเชียงราย อ.สามเงา",river:"แม่น้ำวัง",province:"ตาก",lat:17.3663924,lng:99.1126573,bankfull:6.30,criticalLevel:6.50,sourceType:"official",sourceUrl:"https://water.rid.go.th/flood/namta/water%20excel/Tnorth_DW.htm",thresholdNote:"รายงานกรมชลประทานพบระดับตลิ่ง 6.30 ม. และระดับวิกฤติ 6.50 ม."},
{id:"W.10B",name:"บ้านดอนมูล ต.บ้านแลง",river:"แม่น้ำวัง",province:"ลำปาง",lat:18.51847,lng:99.63271,bankfull:6.60,watchLevel:5.28,sourceType:"official",sourceUrl:"https://www.hydro-1.net/index1.html",thresholdNote:"ระดับตลิ่ง 6.60 ม.; เฝ้าระวังตั้งแต่ 5.28 ม. ตามเอกสารเกณฑ์สถานี"}
].map(s=>({...s,level:null,flow:null,apiLimit:null,readings:[],state:"idle"}));
const visible=new Set(stations.map(s=>s.id));let selected="W.1C",markers={};
const $=id=>document.getElementById(id),map=L.map("map").setView([18.25,99.42],8);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors",maxZoom:19}).addTo(map);
$("date").value=new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Bangkok"});
function n(v){if(v===""||v==null)return null;const z=Number(v);return Number.isFinite(z)?z:null}
function state(s){if(s.state==="loading")return["กำลังโหลด","#0ea5e9"];if(s.level==null)return["ไม่มีข้อมูลระดับน้ำ","#64748b"];if(s.bankfull==null)return["ยังไม่มีเกณฑ์ยืนยัน","#7c3aed"];if(s.level>=s.bankfull)return["ถึงหรือเกินตลิ่ง","#dc2626"];const watch=s.watchLevel??(s.bankfull-1);if(s.level>=watch)return["ใกล้ถึงตลิ่ง/เฝ้าระวัง","#f59e0b"];return["ต่ำกว่าเกณฑ์","#16a34a"]}
function slotData(row,id){const one=String(row.station_id1||"").replace(/\s/g,"").toUpperCase()===id.toUpperCase(),suffix=one?"":"_2",levels=[],flows=[];for(let h=1;h<=24;h++){const a=n(row[`level${h}_day1${suffix}`]),b=n(row[`dischg${h}_day1${suffix}`]);if(a!=null)levels.push(a);if(b!=null)flows.push(b)}return{readings:levels,level:levels.at(-1)??null,flow:flows.at(-1)??null,apiLimit:n(row[one?"level_limit1":"level_limit2"])}}
function jsonp(id,date){return new Promise((resolve,reject)=>{const cb=`hydro_${id.replace(/\W/g,"")}_${Date.now()}_${Math.random().toString(36).slice(2)}`,sc=document.createElement("script"),[y,m,d]=date.split("-");let done=false;const clear=()=>{sc.remove();delete window[cb]};const timer=setTimeout(()=>{if(!done){done=true;clear();reject()}},9000);window[cb]=payload=>{if(done)return;done=true;clearTimeout(timer);clear();const row=Array.isArray(payload)?payload[0]:payload;if(!row)return reject();resolve(slotData(row,id))};sc.onerror=()=>{if(!done){done=true;clearTimeout(timer);clear();reject()}};sc.src=`https://hydro1.ddns.net/main/information_4/houly/water_today_json.php?station_id1=&station_id2=${encodeURIComponent(id)}&date=${d}-${m}-${y}&callback=${cb}`;document.body.appendChild(sc)})}
function renderMap(){Object.values(markers).forEach(m=>map.removeLayer(m));markers={};stations.filter(s=>visible.has(s.id)).forEach(s=>{const [,color]=state(s),icon=L.divIcon({className:"water-icon",html:`<div class="pin" style="--c:${color}"><span>${s.id}</span></div>`,iconSize:[48,48],iconAnchor:[24,43]});markers[s.id]=L.marker([s.lat,s.lng],{icon}).addTo(map).bindTooltip(`${s.id} · ${s.name}`).on("click",()=>{selected=s.id;render()})})}
function chart(values){if(values.length<2)return"ยังไม่มีข้อมูลกราฟ";const min=Math.min(...values),max=Math.max(...values),span=max-min||1,pts=values.map((v,i)=>`${i/(values.length-1)*100},${46-(v-min)/span*38}`).join(" ");return `<svg viewBox="0 0 100 50" preserveAspectRatio="none"><polyline points="${pts}"/></svg>`}
function render(){const q=$("search").value.toLowerCase(),active=stations.find(s=>s.id===selected)||stations[0];$("station-list").innerHTML=stations.filter(s=>(s.id+s.name+s.river).toLowerCase().includes(q)).map(s=>{const [,c]=state(s);return`<button class="station-row ${s.id===selected?"selected":""}" data-id="${s.id}"><input type="checkbox" ${visible.has(s.id)?"checked":""} data-toggle="${s.id}"><i style="background:${c}"></i><span><b>${s.id}</b><small>${s.river} · ${s.name}</small></span><em>${s.level==null?"—":s.level.toFixed(2)+" ม."}</em></button>`}).join("");document.querySelectorAll(".station-row").forEach(b=>b.onclick=e=>{if(e.target.dataset.toggle){const id=e.target.dataset.toggle;e.target.checked?visible.add(id):visible.delete(id);renderMap();renderCount();e.stopPropagation()}else{selected=b.dataset.id;render()}});$("station-id").textContent=active.id;$("station-name").textContent=active.name;$("station-meta").textContent=`${active.river} · จังหวัด${active.province} · พิกัดยืนยันแล้ว`;$("level").textContent=active.level==null?"—":active.level.toFixed(2)+" ม.";$("flow").textContent=active.flow==null?"—":active.flow.toFixed(2)+" ม³/วินาที";$("bankfull").textContent=active.bankfull==null?"ยังไม่มีข้อมูล":active.bankfull.toFixed(2)+" ม.";$("threshold-type").textContent=active.sourceType==="official"?"เกณฑ์ที่มีเอกสารอ้างอิง":active.sourceType==="derived"?"คำนวณจากทะเบียนสถานี":"ยังไม่มีข้อมูลยืนยัน";$("threshold-note").textContent=active.thresholdNote;$("threshold-source").href=active.sourceUrl;const [label,color]=state(active);$("status").textContent=label;$("status").style.color=color;$("status").style.background=color+"18";$("reading-count").textContent=`${active.readings.length} ค่าที่มีข้อมูล`;$("chart").innerHTML=chart(active.readings);$("ok-count").textContent=stations.filter(s=>s.state==="ok").length;renderCount()}
function renderCount(){$("count").textContent=`${visible.size}/${stations.length} สถานีที่แสดง`;$("toggle-all").textContent=visible.size?"ซ่อนทั้งหมด":"แสดงทั้งหมด"}
$("search").oninput=render;$("toggle-all").onclick=()=>{visible.size?visible.clear():stations.forEach(s=>visible.add(s.id));renderMap();render()};
$("refresh").onclick=async()=>{const btn=$("refresh");btn.disabled=true;btn.textContent="กำลังอัปเดต…";$("sync").textContent="กำลังดึงข้อมูลทุกสถานี…";stations.forEach(s=>s.state="loading");render();renderMap();let ok=0;for(const s of stations){try{Object.assign(s,await jsonp(s.id,$("date").value));s.state=s.readings.length?"ok":"missing";if(s.state==="ok")ok++}catch{s.state="missing"}render();renderMap()}$("sync").textContent=`พบข้อมูล ${ok} จาก ${stations.length} สถานี · อัปเดต ${new Date().toLocaleTimeString("th-TH",{hour:"2-digit",minute:"2-digit"})} น.`;btn.disabled=false;btn.textContent="↻ อัปเดตทุกสถานี"};
renderMap();render();map.fitBounds(L.latLngBounds(stations.map(s=>[s.lat,s.lng])),{padding:[35,35]});
