const stations=[
["W.25","บ้านร่องเคาะ อ.วังเหนือ","แม่น้ำวัง","ลำปาง",19.0374,99.6165],["W.16A","บ้านไฮ อ.แจ้ห่ม","แม่น้ำวัง","ลำปาง",18.7853,99.63],
["W.17","บ้านหนองนาว อ.แจ้ห่ม","น้ำแม่สอย","ลำปาง",18.72236,99.56721],["W.26","บ้านห้วยแม่ต๋า อ.แจ้ห่ม","ห้วยแม่ต๋า","ลำปาง",18.59602,99.62205],
["W.21","บ้านท่าเดื่อ อ.เมืองลำปาง","แม่น้ำวัง","ลำปาง",18.34317,99.53699],["W.1C","สะพานเสตุวารี อ.เมืองลำปาง","แม่น้ำวัง","ลำปาง",18.29971,99.51115],
["W.20","บ้านท่าล้อ ต.บ่อแฮ้ว","น้ำแม่ตุ๋ย","ลำปาง",18.31091,99.45782],["W.5A","บ้านเกาะคา ต.ศาลา","แม่น้ำวัง","ลำปาง",18.19161,99.39712],
["W.22","บ้านวังพร้าว อ.เกาะคา","น้ำแม่จาง","ลำปาง",18.14451,99.40839],["W.18A","บ้านสบต๋ำ อ.เกาะคา","น้ำแม่ต๋ำ","ลำปาง",18.07048,99.32276],
["W.6B","บ้านหล่าย อ.สบปราบ","แม่น้ำวัง","ลำปาง",17.89022,99.3279],["W.3A","บ้านดอนชัย อ.เถิน","แม่น้ำวัง","ลำปาง",17.64152,99.2319],
["W.23","บ้านเชียงราย อ.สามเงา","แม่น้ำวัง","ตาก",17.3663924,99.1126573],["W.10B","บ้านดอนมูล ต.บ้านแลง","แม่น้ำวัง","ลำปาง",18.51847,99.63271]
].map(x=>({id:x[0],name:x[1],river:x[2],province:x[3],lat:x[4],lng:x[5],level:null,flow:null,limit:null,readings:[],state:"idle"}));
const visible=new Set(stations.map(s=>s.id));let selected="W.1C",markers={};
const $=id=>document.getElementById(id),map=L.map("map").setView([18.25,99.42],8);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors",maxZoom:19}).addTo(map);
$("date").value=new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Bangkok"});
function n(v){if(v===""||v==null)return null;const z=Number(v);return Number.isFinite(z)?z:null}
function state(s){if(s.state==="loading")return["กำลังโหลด","#0ea5e9"];if(s.level==null)return["ไม่มีข้อมูล","#64748b"];if(s.limit!=null&&s.level>=s.limit)return["เฝ้าระวังสูง","#dc2626"];if(s.limit!=null&&s.level>=s.limit*.8)return["เฝ้าระวัง","#f59e0b"];return["ปกติ","#16a34a"]}
function slotData(row,id){const one=String(row.station_id1||"").replace(/\s/g,"").toUpperCase()===id.toUpperCase(),suffix=one?"":"_2",levels=[],flows=[];for(let h=1;h<=24;h++){const a=n(row[`level${h}_day1${suffix}`]),b=n(row[`dischg${h}_day1${suffix}`]);if(a!=null)levels.push(a);if(b!=null)flows.push(b)}return{readings:levels,level:levels.at(-1)??null,flow:flows.at(-1)??null,limit:n(row[one?"level_limit1":"level_limit2"])}}
function jsonp(id,date){return new Promise((resolve,reject)=>{const cb=`hydro_${id.replace(/\W/g,"")}_${Date.now()}_${Math.random().toString(36).slice(2)}`,sc=document.createElement("script"),[y,m,d]=date.split("-");let done=false;const clear=()=>{sc.remove();delete window[cb]};const timer=setTimeout(()=>{if(!done){done=true;clear();reject()}},9000);window[cb]=payload=>{if(done)return;done=true;clearTimeout(timer);clear();const row=Array.isArray(payload)?payload[0]:payload;if(!row)return reject();resolve(slotData(row,id))};sc.onerror=()=>{if(!done){done=true;clearTimeout(timer);clear();reject()}};sc.src=`https://hydro1.ddns.net/main/information_4/houly/water_today_json.php?station_id1=&station_id2=${encodeURIComponent(id)}&date=${d}-${m}-${y}&callback=${cb}`;document.body.appendChild(sc)})}
function renderMap(){Object.values(markers).forEach(m=>map.removeLayer(m));markers={};stations.filter(s=>visible.has(s.id)).forEach(s=>{const [,color]=state(s),icon=L.divIcon({className:"water-icon",html:`<div class="pin" style="--c:${color}"><span>${s.id}</span></div>`,iconSize:[48,48],iconAnchor:[24,43]});markers[s.id]=L.marker([s.lat,s.lng],{icon}).addTo(map).bindTooltip(`${s.id} · ${s.name}`).on("click",()=>{selected=s.id;render()})})}
function chart(values){if(values.length<2)return"ยังไม่มีข้อมูลกราฟ";const min=Math.min(...values),max=Math.max(...values),span=max-min||1,pts=values.map((v,i)=>`${i/(values.length-1)*100},${46-(v-min)/span*38}`).join(" ");return `<svg viewBox="0 0 100 50" preserveAspectRatio="none"><polyline points="${pts}"/></svg>`}
function render(){const q=$("search").value.toLowerCase(),active=stations.find(s=>s.id===selected)||stations[0];$("station-list").innerHTML=stations.filter(s=>(s.id+s.name+s.river).toLowerCase().includes(q)).map(s=>{const [,c]=state(s);return`<button class="station-row ${s.id===selected?"selected":""}" data-id="${s.id}"><input type="checkbox" ${visible.has(s.id)?"checked":""} data-toggle="${s.id}"><i style="background:${c}"></i><span><b>${s.id}</b><small>${s.river} · ${s.name}</small></span><em>${s.level==null?"—":s.level.toFixed(2)+" ม."}</em></button>`}).join("");document.querySelectorAll(".station-row").forEach(b=>b.onclick=e=>{if(e.target.dataset.toggle){const id=e.target.dataset.toggle;e.target.checked?visible.add(id):visible.delete(id);renderMap();renderCount();e.stopPropagation()}else{selected=b.dataset.id;render()}});$("station-id").textContent=active.id;$("station-name").textContent=active.name;$("station-meta").textContent=`${active.river} · จังหวัด${active.province} · พิกัดยืนยันแล้ว`;$("level").textContent=active.level==null?"—":active.level.toFixed(2)+" ม.";$("flow").textContent=active.flow==null?"—":active.flow.toFixed(2)+" ม³/วินาที";const [label,color]=state(active);$("status").textContent=label;$("status").style.color=color;$("reading-count").textContent=`${active.readings.length} ค่าที่มีข้อมูล`;$("chart").innerHTML=chart(active.readings);$("ok-count").textContent=stations.filter(s=>s.state==="ok").length;renderCount()}
function renderCount(){$("count").textContent=`${visible.size}/${stations.length} สถานีที่แสดง`;$("toggle-all").textContent=visible.size?"ซ่อนทั้งหมด":"แสดงทั้งหมด"}
$("search").oninput=render;$("toggle-all").onclick=()=>{visible.size?visible.clear():stations.forEach(s=>visible.add(s.id));renderMap();render()};
$("refresh").onclick=async()=>{const btn=$("refresh");btn.disabled=true;btn.textContent="กำลังอัปเดต…";$("sync").textContent="กำลังดึงข้อมูลทุกสถานี…";stations.forEach(s=>s.state="loading");render();renderMap();let ok=0;for(const s of stations){try{Object.assign(s,await jsonp(s.id,$("date").value));s.state=s.readings.length?"ok":"missing";if(s.state==="ok")ok++}catch{s.state="missing"}render();renderMap()}$("sync").textContent=`พบข้อมูล ${ok} จาก ${stations.length} สถานี · อัปเดต ${new Date().toLocaleTimeString("th-TH",{hour:"2-digit",minute:"2-digit"})} น.`;btn.disabled=false;btn.textContent="↻ อัปเดตทุกสถานี"};
renderMap();render();map.fitBounds(L.latLngBounds(stations.map(s=>[s.lat,s.lng])),{padding:[35,35]});
